stfalcon_tinymce:
    tinymce:
        tinymce_jquery: true
        tinymce_js_init:
            height: 400
            plugins:
                - link image code
            toolbar: "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | code"